package com.dcnt.take_away_now.enums;
public enum EstadoDelPedido {
    AGUARDANDO_PREPARACION,
    EN_PREPARACION,
    LISTO_PARA_RETIRAR,
    RETIRADO,
    CANCELADO,
    DEVOLUCION_SOLICITADA,
    DEVOLUCION_ACEPTADA,
    DEVOLUCION_DENEGADA
}
